[project]
name = "sql-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ptw9hw", email = "ptw9hw@virginia.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "mysql-connector-python",
    "pandas",
]

[project.scripts]
sql-lab = "sql_lab.process:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
